# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile.txt                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: Adeline <Adeline@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/13 18:38:18 by adbenoit          #+#    #+#              #
#    Updated: 2020/05/27 22:59:31 by Adeline          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		= cub3d

INC			= includes/

# HEADER 		= $(INC)cub3d_utils.h

# HEAD_BONUS	= $(INC)cub3d_bonus.h

HEADER	= $(INC)cub3d.h


SRCS_PATH	= srcs

# BONUS_PATH	= srcs/bonus

O_PARS_PATH	= srcs/obligatory/parsing
OBL_PATH	= srcs/obligatory

RAY_PATH	= srcs/raycasting

UTILS_PATH	= srcs/utils


SRCS_NAME	=	main.c\
				move.c\
				bmp_file.c

# BONUS_NAME	=	create_img_bonus.c\
# 				ft_deal_key_bonus.c\
# 				exit_game_bonus.c\
# 				start_bonus.c\
# 				weapon_bonus.c

O_PARS_NAME	=	check_info.c\
				ft_space.c\
				ft_strtrim.c\
				map.c\
				pars_error.c\
				parsing.c

OBL_NAME	=	create_img.c\
				ft_deal_key.c\
				exit_game.c\
				start.c

RAY_NAME	=	sprite.c\
				texture.c\
				wall.c\
				wall_utils.c


UTILS_NAME	=	ft_atoi.c\
				ft_bzero.c\
				ft_memcpy.c\
				ft_putnbr_fd.c\
				ft_realloc.c\
				get_next_line.c\
				get_next_line_utils.c

OBJ_PATH	= obj
# OBJ_B_PATH	= obj_bonus

OBJ_NAME	= $(SRC:.c=.o)

# OBJ_B_NAME	= $(OBJ_NAME)
# OBJ_B_NAME	+= $(BONUS_NAME:.c=.o)


CC			= gcc

CFLAGS		= -Wall -Werror -Wextra

MLX_DIR		= minilibx

MLX			= $(MLX_DIR)/libmlx.a

MLX_LIBS	= -lmlx -lXext -lX11

SRC			= $(addprefix $(SRCS_PATH)/,$(SRCS_NAME))
SRC			+= $(addprefix $(RAY_PATH)/,$(RAY_NAME))
SRC			+= $(addprefix $(UTILS_PATH)/,$(UTILS_NAME))
SRC			+= $(addprefix $(OBL_PATH)/,$(OBL_NAME))
SRC			+= $(addprefix $(O_PARS_PATH)/,$(O_PARS_NAME))

# OBJ_B		= $(addprefix $(OBJ_B_PATH)/,$(OBJ_B_NAME))

OBJ		= $(addprefix $(OBJ_PATH)/,$(OBJ_NAME))

all: $(MLX) $(NAME)

$(MLX) :
	@make -C $(MLX_DIR) $(MLX_LIBS)
	@echo "Compilation of \033[33;1m$(MLX_DIR)\033[0;1m: [\033[1;32mOK\033[0;1m]"

$(NAME):	$(OBJ)
	@printf "\n"
	@$(CC) -o $(NAME) $(OBJ) $(MLX) -framework OpenGL -framework AppKit
	@echo "Compilation of \033ss[33;1m$(NAME)\033[0;1m: [\033[1;32mOK\033[0;1m]"

# bonus :	$(MLX) $(OBJ_B)
# 	@printf "\n"
# 	@$(CC) -o $(NAME) $(OBJ_B) $(MLX) -framework OpenGL -framework AppKit
# 	@echo "Compilation of \033[33;1m$(NAME) bonus\033[0;1m: [\033[1;32mOK\033[0;1m]"

$(OBJ_PATH)/%.o:	$(OBL_PATH)/%.c $(HEADER)
	@printf "\033[34;1m| \033[0;1m"
	@mkdir $(OBJ_PATH) 2> /dev/null || true
	@$(CC) $(CFLAGS) -I$(INC) -c $< -o $@

$(OBJ_PATH)/%.o:	$(SRCS_PATH)/%.c $(HEADER)
	@printf "\033[34;1m| \033[0;1m"
	@mkdir $(OBJ_PATH) 2> /dev/null || true
	@$(CC) $(CFLAGS) -I$(INC) -c $< -o $@

# $(OBJ_B_PATH)/%.o:	$(BONUS_PATH)/%.c $(SRCS_PATH)/%.c $(RAY_PATH)/%.c $(UTILS_PATH)/%.c $(HEAD_BONUS)
# 	@printf "\033[34;1m| \033[0;1m"
# 	@mkdir $(OBJ_B_PATH) 2> /dev/null || true
# 	@$(CC) $(CFLAGS)  -I$(INC) -c $< -o $@


clean:
	@make -C $(MLX_DIR) clean
	# @rm -f $(OBJ_B)
	@rm -f $(OBJ)
	@rm -rf $(OBJ_PATH)
	# @rm -rf $(OBJ_B_PATH)
	@echo "\033[33;1m$(NAME)\033[0;1m: objects deleted\033[0m"

fclean:	clean
	@rm -rf $(NAME)
	@echo "\033[33;1m$(NAME)\033[0;1m: $(NAME) deleted\033[0m"

re: fclean all

.PHONY: all clean fclean re bonus